fix: from attr import attr, attrs, attrib, Factory ImportError: cannot import name 'attrs' from 'attr' (#127)
* Add tox env verifying plain install (without dev requirements).

* Install attrs instead of attr package.